version: "3"
services:
  app:
    image: node
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - ./:/home/node/app
    command: npm start
